import { db } from "./db";
import { stewards, plots, verificationEvents } from "@shared/schema";

export async function seedDatabase() {
  const existingStewards = await db.select().from(stewards);
  if (existingStewards.length > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database with sample data...");

  const [steward1, steward2, steward3, steward4] = await db.insert(stewards).values([
    {
      name: "Maria Santos",
      phone: "+63 917 123 4567",
      barangay: "San Isidro",
      province: "Bukidnon",
      totalPlots: 3,
      verifiedPlots: 2,
      totalEarnings: 12500,
    },
    {
      name: "Juan dela Cruz",
      phone: "+63 918 234 5678",
      barangay: "Lumbia",
      province: "Misamis Oriental",
      totalPlots: 2,
      verifiedPlots: 1,
      totalEarnings: 8200,
    },
    {
      name: "Rosa Reyes",
      phone: "+63 919 345 6789",
      barangay: "Tagoloan",
      province: "Misamis Oriental",
      totalPlots: 4,
      verifiedPlots: 3,
      totalEarnings: 18750,
    },
    {
      name: "Pedro Gonzales",
      phone: "+63 920 456 7890",
      barangay: "Cagayan de Oro",
      province: "Misamis Oriental",
      totalPlots: 2,
      verifiedPlots: 0,
      totalEarnings: 0,
    },
  ]).returning();

  const [plot1, plot2, plot3, plot4, plot5, plot6] = await db.insert(plots).values([
    {
      name: "Hillside Bamboo Grove",
      stewardId: steward1.id,
      latitude: 7.7234,
      longitude: 125.5823,
      areaHectares: 2.5,
      clumpCount: 45,
      status: "verified",
      healthScore: 85,
      carbonTons: 12.5,
      lastVerified: new Date("2026-01-15"),
    },
    {
      name: "Riverside Plantation",
      stewardId: steward1.id,
      latitude: 7.6891,
      longitude: 125.6234,
      areaHectares: 1.8,
      clumpCount: 32,
      status: "verified",
      healthScore: 92,
      carbonTons: 8.8,
      lastVerified: new Date("2026-01-20"),
    },
    {
      name: "Valley Floor Plot",
      stewardId: steward1.id,
      latitude: 7.7512,
      longitude: 125.5012,
      areaHectares: 3.2,
      clumpCount: 58,
      status: "pending",
      healthScore: 78,
      carbonTons: 15.2,
    },
    {
      name: "Mountain Terrace",
      stewardId: steward2.id,
      latitude: 7.8123,
      longitude: 125.5456,
      areaHectares: 2.1,
      clumpCount: 38,
      status: "verified",
      healthScore: 88,
      carbonTons: 10.5,
      lastVerified: new Date("2026-01-18"),
    },
    {
      name: "Coastal Bamboo Stand",
      stewardId: steward2.id,
      latitude: 7.6234,
      longitude: 125.7123,
      areaHectares: 1.5,
      clumpCount: 25,
      status: "submitted",
      healthScore: 72,
      carbonTons: 6.2,
    },
    {
      name: "Northern Ridge Farm",
      stewardId: steward3.id,
      latitude: 7.8567,
      longitude: 125.4891,
      areaHectares: 4.0,
      clumpCount: 72,
      status: "under_review",
      healthScore: 95,
      carbonTons: 22.0,
    },
    {
      name: "Sunrise Valley Plot",
      stewardId: steward3.id,
      latitude: 7.7891,
      longitude: 125.5678,
      areaHectares: 2.8,
      clumpCount: 50,
      status: "verified",
      healthScore: 90,
      carbonTons: 14.0,
      lastVerified: new Date("2026-01-22"),
    },
    {
      name: "Bamboo Heritage Site",
      stewardId: steward3.id,
      latitude: 7.7012,
      longitude: 125.6567,
      areaHectares: 1.9,
      clumpCount: 35,
      status: "verified",
      healthScore: 82,
      carbonTons: 9.5,
      lastVerified: new Date("2026-01-10"),
    },
    {
      name: "New Growth Area",
      stewardId: steward4.id,
      latitude: 7.6567,
      longitude: 125.5234,
      areaHectares: 2.2,
      clumpCount: 18,
      status: "pending",
      healthScore: 65,
      carbonTons: 4.5,
    },
    {
      name: "Expansion Zone East",
      stewardId: steward4.id,
      latitude: 7.7345,
      longitude: 125.6891,
      areaHectares: 1.6,
      clumpCount: 12,
      status: "pending",
      healthScore: 55,
      carbonTons: 2.8,
    },
  ]).returning();

  await db.insert(verificationEvents).values([
    {
      plotId: plot1.id,
      stewardId: steward1.id,
      eventType: "planting",
      status: "verified",
      evidenceUrls: ["photo1.jpg", "photo2.jpg"],
      notes: "Initial planting verified. 45 clumps planted successfully.",
      verifiedBy: "Carlos Mendez",
      paymentAmount: 5000,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-15"),
    },
    {
      plotId: plot1.id,
      stewardId: steward1.id,
      eventType: "survival_check",
      status: "verified",
      evidenceUrls: ["check1.jpg"],
      notes: "95% survival rate confirmed",
      verifiedBy: "Ana Garcia",
      paymentAmount: 2500,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-20"),
    },
    {
      plotId: plot2.id,
      stewardId: steward1.id,
      eventType: "maintenance",
      status: "verified",
      evidenceUrls: ["maint1.jpg", "maint2.jpg", "maint3.jpg"],
      notes: "Regular maintenance completed. Weeding and mulching done.",
      verifiedBy: "Carlos Mendez",
      paymentAmount: 3000,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-22"),
    },
    {
      plotId: plot3.id,
      stewardId: steward1.id,
      eventType: "growth_measurement",
      status: "pending",
      evidenceUrls: ["growth1.jpg"],
      notes: "Awaiting verification of growth data",
    },
    {
      plotId: plot4.id,
      stewardId: steward2.id,
      eventType: "planting",
      status: "verified",
      evidenceUrls: ["plant_mt1.jpg", "plant_mt2.jpg"],
      notes: "Mountain terrace planting completed",
      verifiedBy: "Ana Garcia",
      paymentAmount: 4200,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-18"),
    },
    {
      plotId: plot5.id,
      stewardId: steward2.id,
      eventType: "survival_check",
      status: "submitted",
      evidenceUrls: ["coastal_check.jpg"],
      notes: "Submitted for review",
    },
    {
      plotId: plot6.id,
      stewardId: steward3.id,
      eventType: "growth_measurement",
      status: "under_review",
      evidenceUrls: ["ridge1.jpg", "ridge2.jpg", "ridge3.jpg", "ridge4.jpg"],
      notes: "Comprehensive growth data submitted for large plot",
    },
  ]);

  console.log("Database seeded successfully!");
}
