import { db } from "./db";
import { projects, stewards, plots, verificationEvents, cooperatives, cooperativeMembers, projectMilestones, projectDocuments } from "@shared/schema";

export async function seedDatabase() {
  const existingStewards = await db.select().from(stewards);
  if (existingStewards.length > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database with sample data...");

  // Create aggregation projects for smallholders
  const [project1, project2] = await db.insert(projects).values([
    {
      name: "Mindanao Bamboo Collective",
      description: "Aggregating smallholder bamboo stewards across Northern Mindanao for carbon credit issuance",
      region: "Northern Mindanao",
      province: "Bukidnon",
      methodology: "verra-bamboo",
      status: "active",
      totalHectares: 15.5,
      totalStewards: 6,
      totalPlots: 8,
      totalCarbonTons: 88.5,
      creditsIssued: 45.2,
      creditsRetired: 12.0,
      vintage: 2025,
      startDate: new Date("2024-03-15"),
    },
    {
      name: "Cagayan de Oro Restoration Initiative",
      description: "New growth bamboo project aggregating stewards in the CDO area",
      region: "Northern Mindanao",
      province: "Misamis Oriental",
      methodology: "gold-standard",
      status: "active",
      totalHectares: 3.8,
      totalStewards: 2,
      totalPlots: 2,
      totalCarbonTons: 7.3,
      creditsIssued: 0,
      creditsRetired: 0,
      vintage: 2026,
      startDate: new Date("2025-06-01"),
    },
  ]).returning();

  const [steward1, steward2, steward3, steward4, steward5, steward6, steward7, steward8] = await db.insert(stewards).values([
    {
      name: "Maria Santos",
      phone: "+63 917 123 4567",
      barangay: "San Isidro",
      province: "Bukidnon",
      totalPlots: 3,
      verifiedPlots: 2,
      totalEarnings: 12500,
    },
    {
      name: "Juan dela Cruz",
      phone: "+63 918 234 5678",
      barangay: "Lumbia",
      province: "Misamis Oriental",
      totalPlots: 2,
      verifiedPlots: 1,
      totalEarnings: 8200,
    },
    {
      name: "Rosa Reyes",
      phone: "+63 919 345 6789",
      barangay: "Tagoloan",
      province: "Misamis Oriental",
      totalPlots: 4,
      verifiedPlots: 3,
      totalEarnings: 18750,
    },
    {
      name: "Pedro Gonzales",
      phone: "+63 920 456 7890",
      barangay: "Cagayan de Oro",
      province: "Misamis Oriental",
      totalPlots: 2,
      verifiedPlots: 0,
      totalEarnings: 0,
    },
    {
      name: "Elena Villanueva",
      phone: "+63 921 567 8901",
      barangay: "Gitagum",
      province: "Misamis Oriental",
      totalPlots: 1,
      verifiedPlots: 1,
      totalEarnings: 6500,
    },
    {
      name: "Roberto Aquino",
      phone: "+63 922 678 9012",
      barangay: "Kimalok",
      province: "Misamis Oriental",
      totalPlots: 1,
      verifiedPlots: 0,
      totalEarnings: 2000,
    },
    {
      name: "Carmen Flores",
      phone: "+63 923 789 0123",
      barangay: "Calacapan",
      province: "Misamis Oriental",
      totalPlots: 1,
      verifiedPlots: 1,
      totalEarnings: 9200,
    },
    {
      name: "Antonio Ramos",
      phone: "+63 924 890 1234",
      barangay: "Taparak",
      province: "Misamis Oriental",
      totalPlots: 1,
      verifiedPlots: 1,
      totalEarnings: 7800,
    },
  ]).returning();

  // Assign plots to projects - all plots around Mt. Anggas region (8.5°N, 124.36°E)
  // First 8 plots go to project1 (Mindanao Bamboo Collective)
  // Last 2 plots go to project2 (CDO Restoration Initiative - new growth area)
  const [plot1, plot2, plot3, plot4, plot5, plot6] = await db.insert(plots).values([
    {
      name: "Hillside Bamboo Grove",
      stewardId: steward1.id,
      projectId: project1.id,
      latitude: 8.502,
      longitude: 124.358,
      areaHectares: 2.5,
      clumpCount: 45,
      status: "verified",
      healthScore: 85,
      carbonTons: 12.5,
      lastVerified: new Date("2026-01-15"),
    },
    {
      name: "Riverside Plantation",
      stewardId: steward1.id,
      projectId: project1.id,
      latitude: 8.495,
      longitude: 124.365,
      areaHectares: 1.8,
      clumpCount: 32,
      status: "verified",
      healthScore: 92,
      carbonTons: 8.8,
      lastVerified: new Date("2026-01-20"),
    },
    {
      name: "Valley Floor Plot",
      stewardId: steward1.id,
      projectId: project1.id,
      latitude: 8.508,
      longitude: 124.352,
      areaHectares: 3.2,
      clumpCount: 58,
      status: "pending",
      healthScore: 78,
      carbonTons: 15.2,
    },
    {
      name: "Mountain Terrace",
      stewardId: steward2.id,
      projectId: project1.id,
      latitude: 8.512,
      longitude: 124.368,
      areaHectares: 2.1,
      clumpCount: 38,
      status: "verified",
      healthScore: 88,
      carbonTons: 10.5,
      lastVerified: new Date("2026-01-18"),
    },
    {
      name: "Anggas Peak Stand",
      stewardId: steward2.id,
      projectId: project1.id,
      latitude: 8.498,
      longitude: 124.355,
      areaHectares: 1.5,
      clumpCount: 25,
      status: "submitted",
      healthScore: 72,
      carbonTons: 6.2,
    },
    {
      name: "Northern Ridge Farm",
      stewardId: steward3.id,
      projectId: project1.id,
      latitude: 8.518,
      longitude: 124.362,
      areaHectares: 4.0,
      clumpCount: 72,
      status: "under_review",
      healthScore: 95,
      carbonTons: 22.0,
    },
    {
      name: "Sunrise Valley Plot",
      stewardId: steward3.id,
      projectId: project1.id,
      latitude: 8.505,
      longitude: 124.372,
      areaHectares: 2.8,
      clumpCount: 50,
      status: "verified",
      healthScore: 90,
      carbonTons: 14.0,
      lastVerified: new Date("2026-01-22"),
    },
    {
      name: "Bamboo Heritage Site",
      stewardId: steward3.id,
      projectId: project1.id,
      latitude: 8.492,
      longitude: 124.348,
      areaHectares: 1.9,
      clumpCount: 35,
      status: "verified",
      healthScore: 82,
      carbonTons: 9.5,
      lastVerified: new Date("2026-01-10"),
    },
    {
      name: "New Growth Area",
      stewardId: steward4.id,
      projectId: project2.id,
      latitude: 8.488,
      longitude: 124.375,
      areaHectares: 2.2,
      clumpCount: 18,
      status: "pending",
      healthScore: 65,
      carbonTons: 4.5,
    },
    {
      name: "Expansion Zone East",
      stewardId: steward4.id,
      projectId: project2.id,
      latitude: 8.515,
      longitude: 124.380,
      areaHectares: 1.6,
      clumpCount: 12,
      status: "pending",
      healthScore: 55,
      carbonTons: 2.8,
    },
  ]).returning();

  await db.insert(verificationEvents).values([
    {
      plotId: plot1.id,
      stewardId: steward1.id,
      eventType: "planting",
      status: "verified",
      evidenceUrls: ["photo1.jpg", "photo2.jpg"],
      notes: "Initial planting verified. 45 clumps planted successfully.",
      verifiedBy: "Carlos Mendez",
      paymentAmount: 5000,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-15"),
    },
    {
      plotId: plot1.id,
      stewardId: steward1.id,
      eventType: "survival_check",
      status: "verified",
      evidenceUrls: ["check1.jpg"],
      notes: "95% survival rate confirmed",
      verifiedBy: "Ana Garcia",
      paymentAmount: 2500,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-20"),
    },
    {
      plotId: plot2.id,
      stewardId: steward1.id,
      eventType: "maintenance",
      status: "verified",
      evidenceUrls: ["maint1.jpg", "maint2.jpg", "maint3.jpg"],
      notes: "Regular maintenance completed. Weeding and mulching done.",
      verifiedBy: "Carlos Mendez",
      paymentAmount: 3000,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-22"),
    },
    {
      plotId: plot3.id,
      stewardId: steward1.id,
      eventType: "growth_measurement",
      status: "pending",
      evidenceUrls: ["growth1.jpg"],
      notes: "Awaiting verification of growth data",
    },
    {
      plotId: plot4.id,
      stewardId: steward2.id,
      eventType: "planting",
      status: "verified",
      evidenceUrls: ["plant_mt1.jpg", "plant_mt2.jpg"],
      notes: "Mountain terrace planting completed",
      verifiedBy: "Ana Garcia",
      paymentAmount: 4200,
      paymentStatus: "paid",
      completedAt: new Date("2026-01-18"),
    },
    {
      plotId: plot5.id,
      stewardId: steward2.id,
      eventType: "survival_check",
      status: "submitted",
      evidenceUrls: ["coastal_check.jpg"],
      notes: "Submitted for review",
    },
    {
      plotId: plot6.id,
      stewardId: steward3.id,
      eventType: "growth_measurement",
      status: "under_review",
      evidenceUrls: ["ridge1.jpg", "ridge2.jpg", "ridge3.jpg", "ridge4.jpg"],
      notes: "Comprehensive growth data submitted for large plot",
    },
  ]);

  // Create cooperatives for project1 (Mindanao Bamboo Collective)
  const [coop1, coop2] = await db.insert(cooperatives).values([
    {
      projectId: project1.id,
      name: "San Isidro Bamboo Farmers Cooperative",
      region: "Bukidnon",
      notes: "Primary cooperative in the San Isidro barangay area",
      memberCount: 2,
    },
    {
      projectId: project1.id,
      name: "Tagoloan Valley Stewards Association",
      region: "Misamis Oriental",
      notes: "Cooperative serving the Tagoloan and Lumbia areas",
      memberCount: 2,
    },
  ]).returning();

  // Link stewards to cooperatives
  await db.insert(cooperativeMembers).values([
    {
      cooperativeId: coop1.id,
      stewardId: steward1.id,
      role: "leader",
    },
    {
      cooperativeId: coop1.id,
      stewardId: steward2.id,
      role: "member",
    },
    {
      cooperativeId: coop2.id,
      stewardId: steward3.id,
      role: "leader",
    },
    {
      cooperativeId: coop2.id,
      stewardId: steward4.id,
      role: "treasurer",
    },
  ]);

  // Create milestones for project1 (in progress project)
  await db.insert(projectMilestones).values([
    {
      projectId: project1.id,
      title: "Initial documentation submission",
      description: "Project Design Document (PDD) and baseline data submitted to registry",
      milestoneType: "documentation",
      status: "completed",
      orderIndex: 1,
      dueDate: new Date("2025-09-15"),
      completedAt: new Date("2025-09-15"),
    },
    {
      projectId: project1.id,
      title: "Public comment period",
      description: "30-day public comment period for stakeholder feedback",
      milestoneType: "public_comment",
      status: "completed",
      orderIndex: 2,
      dueDate: new Date("2026-01-22"),
      completedAt: new Date("2026-01-22"),
    },
    {
      projectId: project1.id,
      title: "Audit kick-off",
      description: "A Validation & Verification Body (VVB) officially commences the project validation and verification process. All VVBs are approved and appointed by Isometric based on the requirements outlined in the Isometric Standard and VVB Policy.",
      milestoneType: "audit",
      status: "in_progress",
      orderIndex: 3,
      dueDate: new Date("2026-03-31"),
    },
    {
      projectId: project1.id,
      title: "Site visit",
      description: "VVB conducts on-site verification of bamboo plots and steward activities",
      milestoneType: "site_visit",
      status: "pending",
      orderIndex: 4,
      dueDate: new Date("2026-06-15"),
    },
    {
      projectId: project1.id,
      title: "Approval date",
      description: "Final approval from registry after successful verification",
      milestoneType: "approval",
      status: "pending",
      orderIndex: 5,
      dueDate: new Date("2026-06-30"),
    },
    {
      projectId: project1.id,
      title: "Initial credit issuance",
      description: "First batch of carbon credits issued based on verified sequestration",
      milestoneType: "credit_issuance",
      status: "pending",
      orderIndex: 6,
      dueDate: new Date("2026-06-30"),
    },
  ]);

  // Create milestones for project2 (newer project)
  await db.insert(projectMilestones).values([
    {
      projectId: project2.id,
      title: "Initial documentation submission",
      description: "Project Design Document (PDD) and baseline data",
      milestoneType: "documentation",
      status: "in_progress",
      orderIndex: 1,
      dueDate: new Date("2026-03-15"),
    },
    {
      projectId: project2.id,
      title: "Public comment period",
      description: "30-day public comment period",
      milestoneType: "public_comment",
      status: "pending",
      orderIndex: 2,
      dueDate: new Date("2026-05-01"),
    },
  ]);

  // Create documents for project1
  await db.insert(projectDocuments).values([
    {
      projectId: project1.id,
      title: "Public Comment Summary",
      documentType: "public_comment",
      fileUrl: "/documents/mbc-public-comment-summary.pdf",
      submittedAt: new Date("2026-01-23"),
    },
    {
      projectId: project1.id,
      title: "PDD",
      documentType: "pdd",
      fileUrl: "/documents/mbc-pdd-v1.pdf",
      submittedAt: new Date("2025-12-24"),
    },
    {
      projectId: project1.id,
      title: "Baseline Assessment Report",
      documentType: "monitoring_report",
      fileUrl: "/documents/mbc-baseline-assessment.pdf",
      submittedAt: new Date("2025-09-10"),
    },
  ]);

  console.log("Database seeded successfully!");
}
